services:
  localstack:
    image: ${MIRROR_PREFIX:-}${LOCALSTACK_IMAGE:-localstack/localstack:4.3}
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_ID:-test}
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - USE_SSL=0
    ports:
      - "${LOCALSTACK_EXPOSED_PORT:-4566}:4566"
    volumes:
      - ./localstack_init.sh:/etc/localstack/init/ready.d/init.sh
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "awslocal s3 ls"]
      interval: 2s
      timeout: 1s
      retries: 10
      start_period: 1s
    # network_mode: host