services:
  minio:
    image: ${MINIO_IMAGE:-quay.io/minio/minio:latest}
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT:-7090}:9000"
      - "${MINIO_CONSOLE_PORT:-7091}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioAccessKey}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioSecretKey}
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  minio-createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 minioAccessKey minioSecretKey;
      /usr/bin/mc mb dockerminio/cop-demo;
      exit 0;
      "
